version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - ./docker/local/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d