spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres_db
    username: username
    password: password
    pool:
      enabled: true
      initial-size: 2
      max-idle-time: 1m
      max-size: 10
  data:
    r2dbc:
      repositories:
        enabled: true
  main:
    web-application-type: reactive

logging:
  level:
    .: DEBUG
    org:
      springframework:
        web:
          filter.CommonsRequestLoggingFilter: INFO
        security: INFO
